#  🍄 SUSTAIN 🍄
### A Practical Example
Inspired by the famous edible-mushroom problem, we aim to solve it using technology from the 80s! I this notebook
we are trying to classify the mushrooms based on their features.

Big shootout for the creators of the dataset: https://archive.ics.uci.edu/dataset/73/mushroom !

### (1) Preprocessing
We will load the dataset and then encode a few chosen features of mushrooms as vectors.

In [44]:
from http.client import responses

import pandas as pd
import os

In [45]:
print(f"working dir: {os.getcwd()}")

working dir: C:\Users\kalus\PycharmProjects\SUSTAIN-replication

In [46]:
df = pd.read_csv("mushrooms.csv", sep=",", encoding="utf-8")
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8124 entries, 0 to 8123
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   class                     8124 non-null   str
 1   cap-shape                 8124 non-null   str
 2   cap-surface               8124 non-null   str
 3   cap-color                 8124 non-null   str
 4   bruises                   8124 non-null   str
 5   odor                      8124 non-null   str
 6   gill-attachment           8124 non-null   str
 7   gill-spacing              8124 non-null   str
 8   gill-size                 8124 non-null   str
 9   gill-color                8124 non-null   str
 10  stalk-shape               8124 non-null   str
 11  stalk-root                8124 non-null   str
 12  stalk-surface-above-ring  8124 non-null   str
 13  stalk-surface-below-ring  8124 non-null   str
 14  stalk-color-above-ring    8124 non-null   str
 15  stalk-color-below-ring    8124 non-null   str
 16  veil-type                 8124 non-null   str
 17  veil-color                8124 non-null   str
 18  ring-number               8124 non-null   str
 19  ring-type                 8124 non-null   str
 20  spore-print-color         8124 non-null   str
 21  population                8124 non-null   str
 22  habitat                   8124 non-null   str
dtypes: str(23)
memory usage: 1.4 MB

In [47]:
df.sample(4)
# the most important variables are class

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
464,e,x,f,n,f,n,f,c,n,k,...,s,w,w,p,w,o,p,k,v,u
6909,p,k,y,e,f,f,f,c,n,b,...,s,w,w,p,w,o,e,w,v,p
3528,e,f,y,e,t,n,f,c,b,p,...,s,p,w,p,w,o,p,k,y,d
1410,e,x,f,n,f,n,f,w,b,k,...,f,w,w,p,w,o,e,k,s,g

What we have to do now is to transform the output into the list readable for SUSTAIN.

In [48]:
X = df[['cap-shape','cap-surface', 'cap-color', 'bruises', 'odor']]
y = df["class"]

In [49]:
# for tests
X = X.head(15)
y = y.head()

In [50]:
# from sklearn.model_selection import train_test_split
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.2, random_state=0, stratify=y)

In [60]:
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder

data = df[['cap-shape','cap-surface', 'cap-color', 'bruises', 'odor']]
data = df.head(30)

# convert to a list
stimuli = []
for row in data.itertuples(index=False):
    row_list = list(row)
    stimuli.append(row_list)

print(f"stimuli: {stimuli}")

# the list consts of string, we need numbers
encoder = OrdinalEncoder()
encoded_stimuli = encoder.fit_transform(stimuli).astype(int).tolist()

# compute the size of dimensions
dim_sizes = [len(categories) for categories in encoder.categories_]
print(f"dim_sizes: {dim_sizes}")
print(f"encoded_stimuli: {encoded_stimuli}")

stimuli: [['p', 'x', 's', 'n', 't', 'p', 'f', 'c', 'n', 'k', 'e', 'e', 's', 's', 'w', 'w', 'p', 'w', 'o', 'p', 'k', 's', 'u'], ['e', 'x', 's', 'y', 't', 'a', 'f', 'c', 'b', 'k', 'e', 'c', 's', 's', 'w', 'w', 'p', 'w', 'o', 'p', 'n', 'n', 'g'], ['e', 'b', 's', 'w', 't', 'l', 'f', 'c', 'b', 'n', 'e', 'c', 's', 's', 'w', 'w', 'p', 'w', 'o', 'p', 'n', 'n', 'm'], ['p', 'x', 'y', 'w', 't', 'p', 'f', 'c', 'n', 'n', 'e', 'e', 's', 's', 'w', 'w', 'p', 'w', 'o', 'p', 'k', 's', 'u'], ['e', 'x', 's', 'g', 'f', 'n', 'f', 'w', 'b', 'k', 't', 'e', 's', 's', 'w', 'w', 'p', 'w', 'o', 'e', 'n', 'a', 'g'], ['e', 'x', 'y', 'y', 't', 'a', 'f', 'c', 'b', 'n', 'e', 'c', 's', 's', 'w', 'w', 'p', 'w', 'o', 'p', 'k', 'n', 'g'], ['e', 'b', 's', 'w', 't', 'a', 'f', 'c', 'b', 'g', 'e', 'c', 's', 's', 'w', 'w', 'p', 'w', 'o', 'p', 'k', 'n', 'm'], ['e', 'b', 'y', 'w', 't', 'l', 'f', 'c', 'b', 'n', 'e', 'c', 's', 's', 'w', 'w', 'p', 'w', 'o', 'p', 'n', 's', 'm'], ['p', 'x', 'y', 'w', 't', 'p', 'f', 'c', 'n', 'p', 'e', 'e', 's', 's', 'w', 'w', 'p', 'w', 'o', 'p', 'k', 'v', 'g'], ['e', 'b', 's', 'y', 't', 'a', 'f', 'c', 'b', 'g', 'e', 'c', 's', 's', 'w', 'w', 'p', 'w', 'o', 'p', 'k', 's', 'm'], ['e', 'x', 'y', 'y', 't', 'l', 'f', 'c', 'b', 'g', 'e', 'c', 's', 's', 'w', 'w', 'p', 'w', 'o', 'p', 'n', 'n', 'g'], ['e', 'x', 'y', 'y', 't', 'a', 'f', 'c', 'b', 'n', 'e', 'c', 's', 's', 'w', 'w', 'p', 'w', 'o', 'p', 'k', 's', 'm'], ['e', 'b', 's', 'y', 't', 'a', 'f', 'c', 'b', 'w', 'e', 'c', 's', 's', 'w', 'w', 'p', 'w', 'o', 'p', 'n', 's', 'g'], ['p', 'x', 'y', 'w', 't', 'p', 'f', 'c', 'n', 'k', 'e', 'e', 's', 's', 'w', 'w', 'p', 'w', 'o', 'p', 'n', 'v', 'u'], ['e', 'x', 'f', 'n', 'f', 'n', 'f', 'w', 'b', 'n', 't', 'e', 's', 'f', 'w', 'w', 'p', 'w', 'o', 'e', 'k', 'a', 'g'], ['e', 's', 'f', 'g', 'f', 'n', 'f', 'c', 'n', 'k', 'e', 'e', 's', 's', 'w', 'w', 'p', 'w', 'o', 'p', 'n', 'y', 'u'], ['e', 'f', 'f', 'w', 'f', 'n', 'f', 'w', 'b', 'k', 't', 'e', 's', 's', 'w', 'w', 'p', 'w', 'o', 'e', 'n', 'a', 'g'], ['p', 'x', 's', 'n', 't', 'p', 'f', 'c', 'n', 'n', 'e', 'e', 's', 's', 'w', 'w', 'p', 'w', 'o', 'p', 'k', 's', 'g'], ['p', 'x', 'y', 'w', 't', 'p', 'f', 'c', 'n', 'n', 'e', 'e', 's', 's', 'w', 'w', 'p', 'w', 'o', 'p', 'n', 's', 'u'], ['p', 'x', 's', 'n', 't', 'p', 'f', 'c', 'n', 'k', 'e', 'e', 's', 's', 'w', 'w', 'p', 'w', 'o', 'p', 'n', 's', 'u'], ['e', 'b', 's', 'y', 't', 'a', 'f', 'c', 'b', 'k', 'e', 'c', 's', 's', 'w', 'w', 'p', 'w', 'o', 'p', 'n', 's', 'm'], ['p', 'x', 'y', 'n', 't', 'p', 'f', 'c', 'n', 'n', 'e', 'e', 's', 's', 'w', 'w', 'p', 'w', 'o', 'p', 'n', 'v', 'g'], ['e', 'b', 'y', 'y', 't', 'l', 'f', 'c', 'b', 'k', 'e', 'c', 's', 's', 'w', 'w', 'p', 'w', 'o', 'p', 'n', 's', 'm'], ['e', 'b', 'y', 'w', 't', 'a', 'f', 'c', 'b', 'w', 'e', 'c', 's', 's', 'w', 'w', 'p', 'w', 'o', 'p', 'n', 'n', 'm'], ['e', 'b', 's', 'w', 't', 'l', 'f', 'c', 'b', 'g', 'e', 'c', 's', 's', 'w', 'w', 'p', 'w', 'o', 'p', 'k', 's', 'm'], ['p', 'f', 's', 'w', 't', 'p', 'f', 'c', 'n', 'n', 'e', 'e', 's', 's', 'w', 'w', 'p', 'w', 'o', 'p', 'n', 'v', 'g'], ['e', 'x', 'y', 'y', 't', 'a', 'f', 'c', 'b', 'n', 'e', 'c', 's', 's', 'w', 'w', 'p', 'w', 'o', 'p', 'n', 'n', 'm'], ['e', 'x', 'y', 'w', 't', 'l', 'f', 'c', 'b', 'w', 'e', 'c', 's', 's', 'w', 'w', 'p', 'w', 'o', 'p', 'n', 'n', 'm'], ['e', 'f', 'f', 'n', 'f', 'n', 'f', 'c', 'n', 'k', 'e', 'e', 's', 's', 'w', 'w', 'p', 'w', 'o', 'p', 'k', 'y', 'u'], ['e', 'x', 's', 'y', 't', 'a', 'f', 'w', 'n', 'n', 't', 'b', 's', 's', 'w', 'w', 'p', 'w', 'o', 'p', 'n', 'v', 'd']]
dim_sizes: [2, 4, 3, 4, 2, 4, 1, 2, 2, 5, 2, 3, 1, 2, 1, 1, 1, 1, 1, 2, 2, 5, 4]
encoded_stimuli: [[1, 3, 1, 1, 1, 3, 0, 0, 1, 1, 0, 2, 0, 1, 0, 0, 0, 0, 0, 1, 0, 2, 3], [0, 3, 1, 3, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1], [0, 0, 1, 2, 1, 1, 0, 0, 0, 2, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 2], [1, 3, 2, 2, 1, 3, 0, 0, 1, 2, 0, 2, 0, 1, 0, 0, 0, 0, 0, 1, 0, 2, 3], [0, 3, 1, 0, 0, 2, 0, 1, 0, 1, 1, 2, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1], [0, 3, 2, 3, 1, 0, 0, 0, 0, 2, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1], [0, 0, 1, 2, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 2], [0, 0, 2, 2, 1, 1, 0, 0, 0, 2, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 2, 2], [1, 3, 2, 2, 1, 3, 0, 0, 1, 3, 0, 2, 0, 1, 0, 0, 0, 0, 0, 1, 0, 3, 1], [0, 0, 1, 3, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 2, 2], [0, 3, 2, 3, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1], [0, 3, 2, 3, 1, 0, 0, 0, 0, 2, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 2, 2], [0, 0, 1, 3, 1, 0, 0, 0, 0, 4, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 2, 1], [1, 3, 2, 2, 1, 3, 0, 0, 1, 1, 0, 2, 0, 1, 0, 0, 0, 0, 0, 1, 1, 3, 3], [0, 3, 0, 1, 0, 2, 0, 1, 0, 2, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], [0, 2, 0, 0, 0, 2, 0, 0, 1, 1, 0, 2, 0, 1, 0, 0, 0, 0, 0, 1, 1, 4, 3], [0, 1, 0, 2, 0, 2, 0, 1, 0, 1, 1, 2, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1], [1, 3, 1, 1, 1, 3, 0, 0, 1, 2, 0, 2, 0, 1, 0, 0, 0, 0, 0, 1, 0, 2, 1], [1, 3, 2, 2, 1, 3, 0, 0, 1, 2, 0, 2, 0, 1, 0, 0, 0, 0, 0, 1, 1, 2, 3], [1, 3, 1, 1, 1, 3, 0, 0, 1, 1, 0, 2, 0, 1, 0, 0, 0, 0, 0, 1, 1, 2, 3], [0, 0, 1, 3, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 2, 2], [1, 3, 2, 1, 1, 3, 0, 0, 1, 2, 0, 2, 0, 1, 0, 0, 0, 0, 0, 1, 1, 3, 1], [0, 0, 2, 3, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 2, 2], [0, 0, 2, 2, 1, 0, 0, 0, 0, 4, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 2], [0, 0, 1, 2, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 2, 2], [1, 1, 1, 2, 1, 3, 0, 0, 1, 2, 0, 2, 0, 1, 0, 0, 0, 0, 0, 1, 1, 3, 1], [0, 3, 2, 3, 1, 0, 0, 0, 0, 2, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 2], [0, 3, 2, 2, 1, 1, 0, 0, 0, 4, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 2], [0, 1, 0, 1, 0, 2, 0, 0, 1, 1, 0, 2, 0, 1, 0, 0, 0, 0, 0, 1, 0, 4, 3], [0, 3, 1, 3, 1, 0, 0, 1, 1, 2, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 3, 0]]

In [61]:
from sustain import SUSTAIN

model = SUSTAIN(r=2.844642,
                beta=2.386305,
                d=12.0,
                eta=0.09361126,
                supervised=True,
                queried_dim=-1)

model.reset(dim_sizes=dim_sizes)  # dim0=feature, dim1=category


index = []
response = []
probability = []
correct = []
n_clusters = []
winner = []
recruited = []


for i, stim in enumerate(encoded_stimuli):
    res = model.present_stimulus(stim, queried_dim=-1)
    index.append(i)
    response.append(res['response'])
    probability.append(res['prob'])
    correct.append(res['correct'])
    n_clusters.append(res['n_clusters'])
    winner.append(res['winner'])
    recruited.append(res['recruited'])


results = pd.DataFrame({
    "index": index,
    "response": response,
    "probability": probability,
    "correct": correct,
    "n_clusters": n_clusters,
    "winner": winner,
    "recruited": recruited
})

results.set_index("index", inplace=True)

In [62]:
results

,response,probability,correct,n_clusters,winner,recruited
index,,,,,,
0,0,"[0.25, 0.25, 0.25, 0.25]",False,1,0,True
1,0,"[0.25, 0.25, 0.25, 0.25]",False,2,1,True
2,0,"[0.25, 0.25, 0.25, 0.25]",False,3,2,True
3,3,"[0.2344109550628432, 0.2344109550628432, 0.234...",True,3,0,False
4,1,"[0.24121150151909154, 0.27636549544272526, 0.2...",True,3,1,False
5,1,"[0.23905226082685316, 0.28284321751944047, 0.2...",True,3,1,False
6,2,"[0.24727285626751241, 0.24727285626751241, 0.2...",True,3,2,False
7,2,"[0.24413527591160636, 0.24413527591160636, 0.2...",True,3,2,False
8,0,"[0.25, 0.25, 0.25, 0.25]",False,4,3,True
9,2,"[0.2462217922529264, 0.2462217922529264, 0.261...",True,4,2,False
10,1,"[0.24383769203713795, 0.268486923888586, 0.243...",True,4,1,False
11,2,"[0.24583860769086113, 0.24583860769086113, 0.2...",True,4,2,False
12,1,"[0.24313997791669983, 0.27058006624990055, 0.2...",True,4,1,False
13,0,"[0.25, 0.25, 0.25, 0.25]",False,5,4,True
14,1,"[0.2451440419366653, 0.26456787419000405, 0.24...",True,5,1,False
15,3,"[0.2498370577703462, 0.2498370577703462, 0.249...",True,5,4,False
16,1,"[0.24507990009259084, 0.2647602997222274, 0.24...",True,5,1,False
17,0,"[0.25, 0.25, 0.25, 0.25]",False,6,5,True
18,3,"[0.24981317065611025, 0.24981317065611025, 0.2...",True,6,4,False
19,3,"[0.24758226836323058, 0.24758226836323058, 0.2...",True,6,0,False
20,2,"[0.2481998436020581, 0.2481998436020581, 0.255...",True,6,2,False
21,1,"[0.24981957344581296, 0.25054127966256107, 0.2...",True,6,3,False
22,2,"[0.24807489940404576, 0.24807489940404576, 0.2...",True,6,2,False
23,2,"[0.24793925936959743, 0.24793925936959743, 0.2...",True,6,2,False
24,2,"[0.24788020599873062, 0.24788020599873062, 0.2...",True,6,2,False
25,1,"[0.24975993803592625, 0.25072018589222117, 0.2...",True,6,3,False
26,2,"[0.24787861629702074, 0.24787861629702074, 0.2...",True,6,2,False
27,2,"[0.24775758800192835, 0.24775758800192835, 0.2...",True,6,2,False
28,3,"[0.24727060884043126, 0.24727060884043126, 0.2...",True,6,0,False
29,0,"[0.25, 0.25, 0.25, 0.25]",False,7,6,True